- name: GitGuardian Shield Action
  # You may pin to the exact commit or the version.
  # uses: GitGuardian/ggshield-action@a5226e0a63850e276df1c71a81129fb82fc6e8cc
  uses: GitGuardian/ggshield-action@v1.1.0
  with:
    # Arguments to be passed to gg-shield scan
Options:
  --show-secrets  Show secrets in plaintext instead of hiding them.
  --exit-zero     Always return a 0 (non-error) status code, even if issues
                  are found. The env var GITGUARDIAN_EXIT_ZERO can also be used
                  to set this option.

  --all-policies  Present fails of all policies (Filenames, FileExtensions,
                  Secret Detection). By default, only Secret Detection is
                  shown.

  -v, --verbose   Verbose display mode.

    args: # optional
